### ISSUE TITLE
Incorrect line ending for `pyIPOPT/setup.py`

### ISSUE THREAD

**Issue by nwu63** [conda-forge/pyoptsparse-feedstock#1]
I believe the CI is failing due to incorrect line ending -- the file in pyOptSparse uses CRLF line endings. This is something I have identified before but never bothered fixing. We can either:
1. Fix this in pyOptSparse and make a patch release, or
2. For now convert the patch in this repo to CRLF to match the line endings.

I would be happy with approach 1) but what do others think?

**Comment by whophil** [comment]
This is very odd. I did indeed have to make the patch have CRLF endings to make this work the first time around. But it is very odd that the this feedstock would have CI behavior that is different from the CI used on `staged-recipes`. Before patching source or recipe, let's see what gitter has to say...

**Comment by nwu63** [comment]
Yeah I'm also surprised that the CI on the PR passed but this failed. Sounds good.
